# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1eb37644f52b059465eefb301abc881225edd93570b16d7e4b392c33072a1138512957ffbb6aed3804e0e1696d77300d9ac46b40b3ef3f6f141001c8872cdcbe

test:
  secret_key_base: b8473c7d8a846da6c0d4fa801415d742878c064bf82bd4aa75300dba2f102fa73a701034e07022eeaadb532a2da7a6a49ada9ef774e789958294a1b03d73389d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
